"""delete soft-delete, Initial again

Revision ID: 25554c67cb98
Revises: 
Create Date: 2026-03-13 20:17:36.496780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25554c67cb98'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advisory_board', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_advisory_board_is_deleted'), table_name='advisory_board')
    op.drop_column('advisory_board', 'is_deleted')
    op.drop_column('advisory_board', 'image_url')
    op.drop_index(op.f('ix_categories_is_deleted'), table_name='categories')
    op.drop_column('categories', 'is_deleted')
    op.drop_index(op.f('ix_events_is_deleted'), table_name='events')
    op.drop_column('events', 'is_deleted')
    op.drop_index(op.f('ix_news_is_deleted'), table_name='news')
    op.drop_column('news', 'is_deleted')
    op.drop_index(op.f('ix_research_clubs_is_deleted'), table_name='research_clubs')
    op.drop_column('research_clubs', 'is_deleted')
    op.drop_index(op.f('ix_research_papers_is_deleted'), table_name='research_papers')
    op.drop_column('research_papers', 'is_deleted')
    op.drop_index(op.f('ix_research_projects_is_deleted'), table_name='research_projects')
    op.drop_column('research_projects', 'is_deleted')
    op.add_column('team_members', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_team_members_is_deleted'), table_name='team_members')
    op.drop_column('team_members', 'is_deleted')
    op.drop_column('team_members', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_members', sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('team_members', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_team_members_is_deleted'), 'team_members', ['is_deleted'], unique=False)
    op.drop_column('team_members', 'image_url')
    op.add_column('research_projects', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_research_projects_is_deleted'), 'research_projects', ['is_deleted'], unique=False)
    op.add_column('research_papers', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_research_papers_is_deleted'), 'research_papers', ['is_deleted'], unique=False)
    op.add_column('research_clubs', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_research_clubs_is_deleted'), 'research_clubs', ['is_deleted'], unique=False)
    op.add_column('news', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_news_is_deleted'), 'news', ['is_deleted'], unique=False)
    op.add_column('events', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_events_is_deleted'), 'events', ['is_deleted'], unique=False)
    op.add_column('categories', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_categories_is_deleted'), 'categories', ['is_deleted'], unique=False)
    op.add_column('advisory_board', sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('advisory_board', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_advisory_board_is_deleted'), 'advisory_board', ['is_deleted'], unique=False)
    op.drop_column('advisory_board', 'image_url')
    # ### end Alembic commands ###
