"""Add created_at timestamps to all tables

Revision ID: 28ce24e6615b
Revises: be00aa4be4f1
Create Date: 2026-02-19 10:00:58.912988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28ce24e6615b'
down_revision: Union[str, Sequence[str], None] = 'be00aa4be4f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advisory_board', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('categories', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('events', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('news', sa.Column('created_by', sa.Integer(), nullable=False))
    op.add_column('news', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'news', 'admins', ['created_by'], ['id'], ondelete='CASCADE')
    op.add_column('publications', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('research_projects', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('team_members', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_members', 'created_at')
    op.drop_column('research_projects', 'created_at')
    op.drop_column('publications', 'created_at')
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.drop_column('news', 'created_at')
    op.drop_column('news', 'created_by')
    op.drop_column('events', 'created_at')
    op.drop_column('categories', 'created_at')
    op.drop_column('advisory_board', 'created_at')
    # ### end Alembic commands ###
