"""create admin table again 

Revision ID: 9aebee9e99d3
Revises: 44f2af539793
Create Date: 2026-02-20 14:59:29.989007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aebee9e99d3'
down_revision: Union[str, Sequence[str], None] = '44f2af539793'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    op.create_foreign_key(None, 'advisory_board', 'admins', ['created_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'categories', 'admins', ['created_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'events', 'admins', ['created_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'news', 'admins', ['created_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'publications', 'admins', ['created_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'research_projects', 'admins', ['created_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'team_members', 'admins', ['created_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.drop_constraint(None, 'research_projects', type_='foreignkey')
    op.drop_constraint(None, 'publications', type_='foreignkey')
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint(None, 'advisory_board', type_='foreignkey')
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
