"""Add telegram fields to admin

Revision ID: b3d94a763e09
Revises: 25554c67cb98
Create Date: 2026-03-16 22:00:26.445849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3d94a763e09'
down_revision: Union[str, Sequence[str], None] = '25554c67cb98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('telegram_chat_id', sa.String(length=100), nullable=True))
    op.add_column('admins', sa.Column('pin_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_admins_telegram_chat_id'), 'admins', ['telegram_chat_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admins_telegram_chat_id'), table_name='admins')
    op.drop_column('admins', 'pin_hash')
    op.drop_column('admins', 'telegram_chat_id')
    # ### end Alembic commands ###
