""" Optimize Database Model

Revision ID: bdaffa78cd91
Revises: 28ce24e6615b
Create Date: 2026-02-19 10:27:01.314147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'bdaffa78cd91'
down_revision: Union[str, Sequence[str], None] = '28ce24e6615b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create ENUM types first
    eventtype_enum = postgresql.ENUM('workshop', 'seminar', 'conference', 'meeting', name='eventtype')
    eventtype_enum.create(op.get_bind(), checkfirst=True)
    
    papertype_enum = postgresql.ENUM('journal', 'conference', 'book', 'report', name='papertype')
    papertype_enum.create(op.get_bind(), checkfirst=True)
    
    projectstatus_enum = postgresql.ENUM('active', 'completed', 'paused', name='projectstatus')
    projectstatus_enum.create(op.get_bind(), checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advisory_board', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('advisory_board', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_advisory_board_created_at'), 'advisory_board', ['created_at'], unique=False)
    op.create_index(op.f('ix_advisory_board_is_active'), 'advisory_board', ['is_active'], unique=False)
    op.create_index(op.f('ix_advisory_board_is_deleted'), 'advisory_board', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_advisory_board_updated_at'), 'advisory_board', ['updated_at'], unique=False)
    op.add_column('categories', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('categories', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.drop_constraint('categories_name_key', 'categories', type_='unique')
    op.create_index(op.f('ix_categories_created_at'), 'categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_categories_is_deleted'), 'categories', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_index(op.f('ix_categories_updated_at'), 'categories', ['updated_at'], unique=False)
    op.add_column('events', sa.Column('slug', sa.String(length=255), nullable=False))
    op.add_column('events', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('events', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.alter_column('events', 'event_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('workshop', 'seminar', 'conference', 'meeting', name='eventtype'),
               nullable=False,
               postgresql_using='event_type::eventtype')
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_is_active'), 'events', ['is_active'], unique=False)
    op.create_index(op.f('ix_events_is_deleted'), 'events', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_events_slug'), 'events', ['slug'], unique=True)
    op.create_index(op.f('ix_events_updated_at'), 'events', ['updated_at'], unique=False)
    op.add_column('news', sa.Column('slug', sa.String(length=255), nullable=False))
    op.add_column('news', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('news', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_news_created_at'), 'news', ['created_at'], unique=False)
    op.create_index(op.f('ix_news_is_deleted'), 'news', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_news_is_published'), 'news', ['is_published'], unique=False)
    op.create_index(op.f('ix_news_published_date'), 'news', ['published_date'], unique=False)
    op.create_index(op.f('ix_news_slug'), 'news', ['slug'], unique=True)
    op.create_index(op.f('ix_news_updated_at'), 'news', ['updated_at'], unique=False)
    op.drop_constraint('project_categories_project_id_fkey', 'project_categories', type_='foreignkey')
    op.drop_constraint('project_categories_category_id_fkey', 'project_categories', type_='foreignkey')
    op.create_foreign_key(None, 'project_categories', 'research_projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_categories', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('project_contributors_member_id_fkey', 'project_contributors', type_='foreignkey')
    op.drop_constraint('project_contributors_project_id_fkey', 'project_contributors', type_='foreignkey')
    op.create_foreign_key(None, 'project_contributors', 'team_members', ['member_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_contributors', 'research_projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('publication_authors_publication_id_fkey', 'publication_authors', type_='foreignkey')
    op.drop_constraint('publication_authors_member_id_fkey', 'publication_authors', type_='foreignkey')
    op.create_foreign_key(None, 'publication_authors', 'publications', ['publication_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'publication_authors', 'team_members', ['member_id'], ['id'], ondelete='CASCADE')
    op.add_column('publications', sa.Column('slug', sa.String(length=255), nullable=False))
    op.add_column('publications', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('publications', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.alter_column('publications', 'paper_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('journal', 'conference', 'book', 'report', name='papertype'),
               nullable=False,
               postgresql_using='paper_type::papertype')
    op.alter_column('publications', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_publications_created_at'), 'publications', ['created_at'], unique=False)
    op.create_index(op.f('ix_publications_is_deleted'), 'publications', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_publications_is_published'), 'publications', ['is_published'], unique=False)
    op.create_index(op.f('ix_publications_paper_type'), 'publications', ['paper_type'], unique=False)
    op.create_index(op.f('ix_publications_publication_date'), 'publications', ['publication_date'], unique=False)
    op.create_index(op.f('ix_publications_slug'), 'publications', ['slug'], unique=True)
    op.create_index(op.f('ix_publications_updated_at'), 'publications', ['updated_at'], unique=False)
    op.drop_constraint('publications_project_id_fkey', 'publications', type_='foreignkey')
    op.create_foreign_key(None, 'publications', 'research_projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('research_projects', sa.Column('slug', sa.String(length=255), nullable=False))
    op.add_column('research_projects', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('research_projects', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.alter_column('research_projects', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('active', 'completed', 'paused', name='projectstatus'),
               nullable=False,
               postgresql_using='status::projectstatus')
    op.alter_column('research_projects', 'budget',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)
    op.create_index(op.f('ix_research_projects_created_at'), 'research_projects', ['created_at'], unique=False)
    op.create_index(op.f('ix_research_projects_is_deleted'), 'research_projects', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_research_projects_is_featured'), 'research_projects', ['is_featured'], unique=False)
    op.create_index(op.f('ix_research_projects_slug'), 'research_projects', ['slug'], unique=True)
    op.create_index(op.f('ix_research_projects_status'), 'research_projects', ['status'], unique=False)
    op.create_index(op.f('ix_research_projects_updated_at'), 'research_projects', ['updated_at'], unique=False)
    op.add_column('team_members', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('team_members', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_team_members_created_at'), 'team_members', ['created_at'], unique=False)
    op.create_index(op.f('ix_team_members_is_active'), 'team_members', ['is_active'], unique=False)
    op.create_index(op.f('ix_team_members_is_deleted'), 'team_members', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_team_members_name'), 'team_members', ['name'], unique=False)
    op.create_index(op.f('ix_team_members_updated_at'), 'team_members', ['updated_at'], unique=False)
    op.create_unique_constraint(None, 'team_members', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team_members', type_='unique')
    op.drop_index(op.f('ix_team_members_updated_at'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_name'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_is_deleted'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_is_active'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_created_at'), table_name='team_members')
    op.drop_column('team_members', 'is_deleted')
    op.drop_column('team_members', 'updated_at')
    op.drop_index(op.f('ix_research_projects_updated_at'), table_name='research_projects')
    op.drop_index(op.f('ix_research_projects_status'), table_name='research_projects')
    op.drop_index(op.f('ix_research_projects_slug'), table_name='research_projects')
    op.drop_index(op.f('ix_research_projects_is_featured'), table_name='research_projects')
    op.drop_index(op.f('ix_research_projects_is_deleted'), table_name='research_projects')
    op.drop_index(op.f('ix_research_projects_created_at'), table_name='research_projects')
    op.alter_column('research_projects', 'budget',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('research_projects', 'status',
               existing_type=sa.Enum('active', 'completed', 'paused', name='projectstatus'),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('research_projects', 'is_deleted')
    op.drop_column('research_projects', 'updated_at')
    op.drop_column('research_projects', 'slug')
    op.drop_constraint(None, 'publications', type_='foreignkey')
    op.create_foreign_key('publications_project_id_fkey', 'publications', 'research_projects', ['project_id'], ['id'])
    op.drop_index(op.f('ix_publications_updated_at'), table_name='publications')
    op.drop_index(op.f('ix_publications_slug'), table_name='publications')
    op.drop_index(op.f('ix_publications_publication_date'), table_name='publications')
    op.drop_index(op.f('ix_publications_paper_type'), table_name='publications')
    op.drop_index(op.f('ix_publications_is_published'), table_name='publications')
    op.drop_index(op.f('ix_publications_is_deleted'), table_name='publications')
    op.drop_index(op.f('ix_publications_created_at'), table_name='publications')
    op.alter_column('publications', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('publications', 'paper_type',
               existing_type=sa.Enum('journal', 'conference', 'book', 'report', name='papertype'),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('publications', 'is_deleted')
    op.drop_column('publications', 'updated_at')
    op.drop_column('publications', 'slug')
    op.drop_constraint(None, 'publication_authors', type_='foreignkey')
    op.drop_constraint(None, 'publication_authors', type_='foreignkey')
    op.create_foreign_key('publication_authors_member_id_fkey', 'publication_authors', 'team_members', ['member_id'], ['id'])
    op.create_foreign_key('publication_authors_publication_id_fkey', 'publication_authors', 'publications', ['publication_id'], ['id'])
    op.drop_constraint(None, 'project_contributors', type_='foreignkey')
    op.drop_constraint(None, 'project_contributors', type_='foreignkey')
    op.create_foreign_key('project_contributors_project_id_fkey', 'project_contributors', 'research_projects', ['project_id'], ['id'])
    op.create_foreign_key('project_contributors_member_id_fkey', 'project_contributors', 'team_members', ['member_id'], ['id'])
    op.drop_constraint(None, 'project_categories', type_='foreignkey')
    op.drop_constraint(None, 'project_categories', type_='foreignkey')
    op.create_foreign_key('project_categories_category_id_fkey', 'project_categories', 'categories', ['category_id'], ['id'])
    op.create_foreign_key('project_categories_project_id_fkey', 'project_categories', 'research_projects', ['project_id'], ['id'])
    op.drop_index(op.f('ix_news_updated_at'), table_name='news')
    op.drop_index(op.f('ix_news_slug'), table_name='news')
    op.drop_index(op.f('ix_news_published_date'), table_name='news')
    op.drop_index(op.f('ix_news_is_published'), table_name='news')
    op.drop_index(op.f('ix_news_is_deleted'), table_name='news')
    op.drop_index(op.f('ix_news_created_at'), table_name='news')
    op.drop_column('news', 'is_deleted')
    op.drop_column('news', 'updated_at')
    op.drop_column('news', 'slug')
    op.drop_index(op.f('ix_events_updated_at'), table_name='events')
    op.drop_index(op.f('ix_events_slug'), table_name='events')
    op.drop_index(op.f('ix_events_is_deleted'), table_name='events')
    op.drop_index(op.f('ix_events_is_active'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.alter_column('events', 'event_type',
               existing_type=sa.Enum('workshop', 'seminar', 'conference', 'meeting', name='eventtype'),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('events', 'is_deleted')
    op.drop_column('events', 'updated_at')
    op.drop_column('events', 'slug')
    op.drop_index(op.f('ix_categories_updated_at'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_is_deleted'), table_name='categories')
    op.drop_index(op.f('ix_categories_created_at'), table_name='categories')
    op.create_unique_constraint('categories_name_key', 'categories', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('categories', 'is_deleted')
    op.drop_column('categories', 'updated_at')
    op.drop_index(op.f('ix_advisory_board_updated_at'), table_name='advisory_board')
    op.drop_index(op.f('ix_advisory_board_is_deleted'), table_name='advisory_board')
    op.drop_index(op.f('ix_advisory_board_is_active'), table_name='advisory_board')
    op.drop_index(op.f('ix_advisory_board_created_at'), table_name='advisory_board')
    op.drop_column('advisory_board', 'is_deleted')
    op.drop_column('advisory_board', 'updated_at')
    
    # Drop ENUM types
    eventtype_enum = postgresql.ENUM('workshop', 'seminar', 'conference', 'meeting', name='eventtype')
    eventtype_enum.drop(op.get_bind(), checkfirst=True)
    
    papertype_enum = postgresql.ENUM('journal', 'conference', 'book', 'report', name='papertype')
    papertype_enum.drop(op.get_bind(), checkfirst=True)
    
    projectstatus_enum = postgresql.ENUM('active', 'completed', 'paused', name='projectstatus')
    projectstatus_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###