"""Fix foreign key relationships

Revision ID: be00aa4be4f1
Revises: 
Create Date: 2026-02-18 20:16:31.614686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be00aa4be4f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advisory_board', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'advisory_board', 'admins', ['created_by'], ['id'], ondelete='CASCADE')
    op.add_column('categories', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'categories', 'admins', ['created_by'], ['id'], ondelete='CASCADE')
    op.add_column('events', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'events', 'admins', ['created_by'], ['id'], ondelete='CASCADE')
    op.add_column('research_projects', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'research_projects', 'admins', ['created_by'], ['id'], ondelete='CASCADE')
    op.add_column('team_members', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'team_members', 'admins', ['created_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.drop_column('team_members', 'created_by')
    op.drop_constraint(None, 'research_projects', type_='foreignkey')
    op.drop_column('research_projects', 'created_by')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'created_by')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'created_by')
    op.drop_constraint(None, 'advisory_board', type_='foreignkey')
    op.drop_column('advisory_board', 'created_by')
    # ### end Alembic commands ###
