"""Initial migration

Revision ID: c2c776d80b5b
Revises: 
Create Date: 2026-02-24 01:09:52.951738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2c776d80b5b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    op.create_table('advisory_board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('institution', sa.String(length=200), nullable=True),
    sa.Column('expertise', sa.String(length=200), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advisory_board_created_at'), 'advisory_board', ['created_at'], unique=False)
    op.create_index(op.f('ix_advisory_board_id'), 'advisory_board', ['id'], unique=False)
    op.create_index(op.f('ix_advisory_board_is_active'), 'advisory_board', ['is_active'], unique=False)
    op.create_index(op.f('ix_advisory_board_is_deleted'), 'advisory_board', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_advisory_board_updated_at'), 'advisory_board', ['updated_at'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_created_at'), 'categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_is_deleted'), 'categories', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_index(op.f('ix_categories_updated_at'), 'categories', ['updated_at'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('event_type', sa.Enum('workshop', 'seminar', 'conference', 'meeting', name='eventtype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_is_active'), 'events', ['is_active'], unique=False)
    op.create_index(op.f('ix_events_is_deleted'), 'events', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_events_slug'), 'events', ['slug'], unique=True)
    op.create_index(op.f('ix_events_updated_at'), 'events', ['updated_at'], unique=False)
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_created_at'), 'news', ['created_at'], unique=False)
    op.create_index(op.f('ix_news_id'), 'news', ['id'], unique=False)
    op.create_index(op.f('ix_news_is_deleted'), 'news', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_news_is_published'), 'news', ['is_published'], unique=False)
    op.create_index(op.f('ix_news_published_date'), 'news', ['published_date'], unique=False)
    op.create_index(op.f('ix_news_slug'), 'news', ['slug'], unique=True)
    op.create_index(op.f('ix_news_updated_at'), 'news', ['updated_at'], unique=False)
    op.create_table('research_clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('core_theme', sa.String(length=300), nullable=True),
    sa.Column('leaders', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_clubs_created_at'), 'research_clubs', ['created_at'], unique=False)
    op.create_index(op.f('ix_research_clubs_id'), 'research_clubs', ['id'], unique=False)
    op.create_index(op.f('ix_research_clubs_is_active'), 'research_clubs', ['is_active'], unique=False)
    op.create_index(op.f('ix_research_clubs_is_deleted'), 'research_clubs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_research_clubs_slug'), 'research_clubs', ['slug'], unique=True)
    op.create_index(op.f('ix_research_clubs_updated_at'), 'research_clubs', ['updated_at'], unique=False)
    op.create_table('research_papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('authors', sa.String(length=500), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('paper_type', sa.Enum('journal', 'conference', 'workshop', 'book_chapter', 'thesis', 'technical_report', 'preprint', 'poster', name='papertype'), nullable=False),
    sa.Column('pdf_url', sa.String(length=255), nullable=True),
    sa.Column('online_url', sa.String(length=255), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_papers_created_at'), 'research_papers', ['created_at'], unique=False)
    op.create_index(op.f('ix_research_papers_id'), 'research_papers', ['id'], unique=False)
    op.create_index(op.f('ix_research_papers_is_deleted'), 'research_papers', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_research_papers_is_published'), 'research_papers', ['is_published'], unique=False)
    op.create_index(op.f('ix_research_papers_paper_type'), 'research_papers', ['paper_type'], unique=False)
    op.create_index(op.f('ix_research_papers_published_date'), 'research_papers', ['published_date'], unique=False)
    op.create_index(op.f('ix_research_papers_slug'), 'research_papers', ['slug'], unique=True)
    op.create_index(op.f('ix_research_papers_updated_at'), 'research_papers', ['updated_at'], unique=False)
    op.create_table('research_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('active', 'completed', 'upcoming', 'paused', name='projectstatus'), nullable=False),
    sa.Column('funding_source', sa.String(length=100), nullable=True),
    sa.Column('budget', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_projects_created_at'), 'research_projects', ['created_at'], unique=False)
    op.create_index(op.f('ix_research_projects_id'), 'research_projects', ['id'], unique=False)
    op.create_index(op.f('ix_research_projects_is_deleted'), 'research_projects', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_research_projects_is_featured'), 'research_projects', ['is_featured'], unique=False)
    op.create_index(op.f('ix_research_projects_slug'), 'research_projects', ['slug'], unique=True)
    op.create_index(op.f('ix_research_projects_status'), 'research_projects', ['status'], unique=False)
    op.create_index(op.f('ix_research_projects_updated_at'), 'research_projects', ['updated_at'], unique=False)
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_team_members_created_at'), 'team_members', ['created_at'], unique=False)
    op.create_index(op.f('ix_team_members_id'), 'team_members', ['id'], unique=False)
    op.create_index(op.f('ix_team_members_is_active'), 'team_members', ['is_active'], unique=False)
    op.create_index(op.f('ix_team_members_is_deleted'), 'team_members', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_team_members_name'), 'team_members', ['name'], unique=False)
    op.create_index(op.f('ix_team_members_updated_at'), 'team_members', ['updated_at'], unique=False)
    op.create_table('project_categories',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'category_id')
    )
    op.create_table('project_contributors',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['team_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'member_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_contributors')
    op.drop_table('project_categories')
    op.drop_index(op.f('ix_team_members_updated_at'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_name'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_is_deleted'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_is_active'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_created_at'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_research_projects_updated_at'), table_name='research_projects')
    op.drop_index(op.f('ix_research_projects_status'), table_name='research_projects')
    op.drop_index(op.f('ix_research_projects_slug'), table_name='research_projects')
    op.drop_index(op.f('ix_research_projects_is_featured'), table_name='research_projects')
    op.drop_index(op.f('ix_research_projects_is_deleted'), table_name='research_projects')
    op.drop_index(op.f('ix_research_projects_id'), table_name='research_projects')
    op.drop_index(op.f('ix_research_projects_created_at'), table_name='research_projects')
    op.drop_table('research_projects')
    op.drop_index(op.f('ix_research_papers_updated_at'), table_name='research_papers')
    op.drop_index(op.f('ix_research_papers_slug'), table_name='research_papers')
    op.drop_index(op.f('ix_research_papers_published_date'), table_name='research_papers')
    op.drop_index(op.f('ix_research_papers_paper_type'), table_name='research_papers')
    op.drop_index(op.f('ix_research_papers_is_published'), table_name='research_papers')
    op.drop_index(op.f('ix_research_papers_is_deleted'), table_name='research_papers')
    op.drop_index(op.f('ix_research_papers_id'), table_name='research_papers')
    op.drop_index(op.f('ix_research_papers_created_at'), table_name='research_papers')
    op.drop_table('research_papers')
    op.drop_index(op.f('ix_research_clubs_updated_at'), table_name='research_clubs')
    op.drop_index(op.f('ix_research_clubs_slug'), table_name='research_clubs')
    op.drop_index(op.f('ix_research_clubs_is_deleted'), table_name='research_clubs')
    op.drop_index(op.f('ix_research_clubs_is_active'), table_name='research_clubs')
    op.drop_index(op.f('ix_research_clubs_id'), table_name='research_clubs')
    op.drop_index(op.f('ix_research_clubs_created_at'), table_name='research_clubs')
    op.drop_table('research_clubs')
    op.drop_index(op.f('ix_news_updated_at'), table_name='news')
    op.drop_index(op.f('ix_news_slug'), table_name='news')
    op.drop_index(op.f('ix_news_published_date'), table_name='news')
    op.drop_index(op.f('ix_news_is_published'), table_name='news')
    op.drop_index(op.f('ix_news_is_deleted'), table_name='news')
    op.drop_index(op.f('ix_news_id'), table_name='news')
    op.drop_index(op.f('ix_news_created_at'), table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_events_updated_at'), table_name='events')
    op.drop_index(op.f('ix_events_slug'), table_name='events')
    op.drop_index(op.f('ix_events_is_deleted'), table_name='events')
    op.drop_index(op.f('ix_events_is_active'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_categories_updated_at'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_is_deleted'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_created_at'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_advisory_board_updated_at'), table_name='advisory_board')
    op.drop_index(op.f('ix_advisory_board_is_deleted'), table_name='advisory_board')
    op.drop_index(op.f('ix_advisory_board_is_active'), table_name='advisory_board')
    op.drop_index(op.f('ix_advisory_board_id'), table_name='advisory_board')
    op.drop_index(op.f('ix_advisory_board_created_at'), table_name='advisory_board')
    op.drop_table('advisory_board')
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
