"""Remove telegram fields to admin

Revision ID: da6af02710b2
Revises: b3d94a763e09
Create Date: 2026-03-16 23:18:04.945538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da6af02710b2'
down_revision: Union[str, Sequence[str], None] = 'b3d94a763e09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admins_telegram_chat_id'), table_name='admins')
    op.drop_column('admins', 'telegram_chat_id')
    op.drop_column('admins', 'pin_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('pin_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('admins', sa.Column('telegram_chat_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_admins_telegram_chat_id'), 'admins', ['telegram_chat_id'], unique=True)
    # ### end Alembic commands ###
