"""update model amdin with avatar

Revision ID: f8c6ffbf9052
Revises: bdaffa78cd91
Create Date: 2026-02-20 12:39:41.660492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8c6ffbf9052'
down_revision: Union[str, Sequence[str], None] = 'bdaffa78cd91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('avatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'avatar')
    # ### end Alembic commands ###
